### ISSUE TITLE
git error

### ISSUE THREAD

**Issue by xinrui-zhuang** [ArthurFirmino/progressive-denoising#1]
hello, when I run the command "git apply ../oidn_patch/pd.patch", there are some git conflicts， is that right？Is it related to the version of OIDN?
very grateful for your work～

**Comment by ArthurFirmino** [comment]
Hi, the commands should work if run as in the readme, and the version of OIDN should be as it in the repo (the same version you'll get if you clone this repo with --recurse-submodules option).

Make sure you also run the 'git apply ...' command from within the 'oidn' directory. If that doesn't fix it you can try posting your error message here.

**Comment by xinrui-zhuang** [comment]
![image](https://user-images.githubusercontent.com/37092207/164450478-4acb7a72-4e57-4cf7-b508-4683d4f7a239.png)
here is the information after  "git apply ../oidn_patch/pd.patch" in “oidn” folder

**Comment by ArthurFirmino** [comment]
Okay, seems it is related to different line-ending conventions between Windows and Linux. I don't have a Windows machine to test, but you could try one of these two commands:

`git apply --ignore-whitespace ../oidn_patch/pd.patch` or, 
`git apply --whitespace=fix ../oidn_patch/pd.patch`
